### ISSUE TITLE
Multiple-Tracks & Button Configs?

### ISSUE THREAD

**Issue by Benjamoose** [ryancog/ProffieConfig#1]
Hi there! First time Proffie owner here!

First of all I want to thank you sincerely for the effort of putting this software together.

As a tinkerer/modder I would have been capable of figuring out the process of setting up the Arduino, etc ultimately, to me it's needlessly tedious when something like your wonderfully robust and streamlined tool can exist in it's place.

As far as I'm concerned this thing should be the official way to manage a Proffie saber!

That's said, I have a couple of thoughts. Basically two road blocks I faced with no immediately obvious solution in the tool (road blocks that I imagine are much easier to resolve when building your own prop files and the like manually, but I'm also admittedly a newbie at this stuff):

1. I really wanted to take advantage of the **many** options in Fett263's drop-down, but wasn't yet ready to commit to learning a whole different setup for the button shortcuts. Could there be a way to use the "default" button shortcuts layout from one drop-down but still then have access to the other options in another?

For example; Fett263's drop-down has options for voice battery percentage. The others don't, but then I have to commit to a whole different shortcut list to use  them.

But it's also completely possible that I'm just ignorant to the limitations of the system or missing something.

2. I installed a sound font that came with its own internal "tracks" folder with multiple tracks. As I understand it, it should be able to cycle between them on activating music. The problem I'm having is that when setting up a preset for the font (to add it to the roster as it were), it wants me to define only one track file with the ".wav" part permanently appended.

As I mentioned before, I imagine that's easier to resolve manually, but I couldn't seem to figure out a way to get it to just use that folder.

Other than that, this is my first ProffieBoard and I've been throughly impressed and thankful for your tool!

**Comment by ryancog** [comment]
> As far as I'm concerned this thing should be the official way to manage a Proffie saber!

Why thank you, I sincerely appreciate it! :)

> Could there be a way to use the "default" button shortcuts layout from one drop-down but still then have access to the other options in another?

This unfortunately is a limitation of the ProffieOS prop file system. Prop files contain all the button mappings for different controls, but for a lot of controls there is custom code to facilitate, for example, the voice battery percentage.

As it stands, there's not a "clean" way to do what you're wanting, due to the way certain prop-specific features and the mappings are intermingled. However, if you're willing to take a look at the code behind the scenes, it should be possible with relatively minimal effort to create your own prop file (based off another one) and add in the control you're wanting.

First, I'll explain things a bit: In ProffieOS there are so-called "prop files" which determine the button mappings, and certain other *things*. In order to present all the options of a prop file to you, ProffieConfig uses a "pconf" file that contains all the data about a prop file and its options.

So, there'd be two steps to this, copy the prop file which has the "base" controls that you like, and then add in the feature you want to it. The actual ProffieOS code resides within ProffieConfig's `resources` folder. The link below about `.pconf`s tells you where to find that.

I'll link [this guide about editing/creating `pconf`s](https://github.com/ryancog/ProffieConfig/blob/master/docs/pconfs.md). It's not entirely complete (iirc it's missing explanation of the `BUTTONS` section, but looking through other props should make that pretty self-explanatory, and I can answer any questions if you're wanting to do this).

I'll also link [this ProffieOSDocs page about making a prop file](https://pod.hubbe.net/howto/making-your-own-prop-file.html) which gives a quick overview about how things kind of work inside those prop files.

Essentially, it should be as easy(ish) as 
1. Copying [this function](https://github.com/profezzorn/ProffieOS/blob/85946ff872ecd4cc2d8d56896371ee72f0d8c48b/props/saber_fett263_buttons.h#L4748-L4762) into the prop file (at the top)
1. Adding [these lines](https://github.com/profezzorn/ProffieOS/blob/85946ff872ecd4cc2d8d56896371ee72f0d8c48b/props/saber_fett263_buttons.h#L6372-L6374) inside the SB_Effect function in your prop file (Check to see if the effect is already handled in your prop... you might need to replace it!)
1. Adding [the effect declaration](https://github.com/profezzorn/ProffieOS/blob/85946ff872ecd4cc2d8d56896371ee72f0d8c48b/props/saber_fett263_buttons.h#L944C1-L944C45) if it's not there already.
1. Adding [these lines](https://github.com/profezzorn/ProffieOS/blob/85946ff872ecd4cc2d8d56896371ee72f0d8c48b/props/saber_fett263_buttons.h#L5739-L5742) into the list of `EVENTID`s. Once again double check to make sure this button mapping isn't already use.

And then you can create a new `pconf` and add the option and button mappings into it, and follow the steps outlined in the guide.

It's not "easy" per-se, but if you're willing to tinker it shouldn't be so difficult that I'd say it's not even worth trying. And of course, if you run into any roadblocks and/or are confused with anything, just ask. :)

> I installed a sound font that came with its own internal "tracks" folder with multiple tracks. As I understand it, it should be able to cycle between them on activating music. The problem I'm having is that when setting up a preset for the font (to add it to the roster as it were), it wants me to define only one track file with the ".wav" part permanently appended.

So yes and no. Fett's prop file, for example, has a "Track Player" feature which *does* cycle through different track files and is able to play multiple. However by default in ProffieOS only a single track file is linked to a preset.

In this case, there's two different mechanisms in play: the default ProffieOS setup, and a custom prop-specific player that bypasses that completely to implement that multi-track feature.

> Other than that, this is my first ProffieBoard and I've been throughly impressed and thankful for your tool!

Glad it's been helpful and things have been going well for you so far. Once again, if you have any more questions, comments, etc., don't hesitate to reach out!

**Comment by ryancog** [comment]
> Ah! Good to know. So, in the case of my situation, could I just:
> 
> For universal support and picking a single track as standard (SA22C, etc) ; direct right into the sound font's track folder and pick a track. Sort of like:
Track: "fonts/FONTNAME/tracks/TRACKNAME.wav"* in the track box, then...
> 
> When using Fett263, regardless of what I have set in there, it'll just override based on it's cycling track player?

Precisely, yep!

> *I have my sound fonts in a "fonts" directory on the root of the SD card to try and keep things tidy.*

If you don’t experience any issues with this, then you’re all good. However I’ll note that this extra “layer” with a slower SD card (or busier blade styles) could slow things down noticeably. With Fat32 extra directories to traverse generally takes more time, so just something to be aware of. 

> you can just name the file, but it doesn't seem to work for ones in a "tracks" subfolder beyond that.

How do you mean? Does the software not let you type it in properly (in which case that’d be a bug), or can you type it in but it simply doesn’t work on the saber?

If it’s the latter, what exactly are you typing in?

**Comment by ryancog** [comment]
> Noice. It seems that the fonts that were previously dumping their tracks untidily into an SD root "tracks" folder are now no longer seeing their tracks. I assume this is just due to the different tracks format in the Fett263 prop file?

There's two different controls for tracks w/ Fett's prop. One to trigger the preset track and one to enable the "Track Player."

If you're using the preset track it, and the track worked on another prop, it should still work.

> It is it because it's now using a "common" folder. As in, should I move the root "tracks" folder there? It's no big deal either way as I can always just put the individual tracks in a "tracks" folder inside the individual fonts.

No, that shouldn't cause issues, but it's possible if your font folder had `;tracks` added to it, Fett's prop file will erase that. (i.e. any additional folder directories besides `;common` are erased)

If there's a `tracks` folder at the root of the SD Card, then you should be able to reference that with `/tracks/` in the "Track File" entry. Note the leading `/`, which indicates to start looking at the root of the sd card, and not the font directory. (For example: `/tracks/track1.wav`)

> So, basically, I was saying "given trackname.wav is actually only one folder deeper, is there a handy short way I can tell the box that without pathing all the way from the root of the SD card".

Yep, just (following from the earlier example) don't include the leading `/` and that'll  do it.

Example being `/tracks/track1.wav` will point to a `track1` file inside a `tracks` folder at the root of the SD card, but `tracks/track1.wav` will point to a `track1` file inside a `tracks` folder inside the current font directory/directories.

**Comment by ryancog** [comment]
> Does that mean outside of Fett's file you could specify multiple folders at once?

Yeah. That's exactly what you're doing with `;common`, in fact. Fett's just allows *only* `;common` whereas on other props you can have a bunch. I've seen a few different use cases, but it's not super common. (no pun intended :laughing:)

> Is there a way to test sound fonts in the blade style editor? I know there is a way to upload individual .wav files to the browser version by Fett, but it'd be great if you could just point the .exe version at a folder then swing the 3D saber about and test buttons.

Not that I'm aware of. It's a technical challenge to try and recreate the way the audio would sound on the board. When you mean `.exe version` do you mean what opens when you choose Tools->Style Editor? If so, then that's just a local copy of the [ProffieOS Style Editor](https://github.com/profezzorn/ProffieOS-StyleEditor).

V2 will have its own Style Editor, and if you think it'd be useful I could put it on the todo to make it play font sounds. However it'd still only be the static effect sounds, not smoothswing. (The preview won't be able to swing like the aforementioned one due to, once again, technical limitations, but maybe just the normal sounds would be useful?)

> It was probably covered in the tutorial at launch, but what are the benefits of the blade array section?
I find myself not really using it and have all my presets and styles under one array.

Separate blade arrays are used for Blade Awareness. So, if you have different types of blades with ID resistors inside, you can change the blade configuration to automatically reflect that. If you have a removable chassis, you could add ID resistors or you detection to change effects based on whether it was removed or not. You could also just change preset arrays based on whether a blade was in the saber or not. Lots of those types of applications. 

> Is it just for organization? Like a category of presets (e.g. "original trilogy", "fun sabers", etc) or does it have a more technical usage like defining multiple blades or something (e.g. a cross guard saber).

Well, there's two parts to the blade arrays page. One is adding/editing blades for a particular array. In which case, yes, a cross guard would be a good example where you might add another blade for the quillions.

What I was referring to above was that you can have multiple blade arrays with completely different sets of blades with its own set of presets.

**Comment by ryancog** [comment]
> Any particular reason why Fett's strips it out or ignores it? Just a case of it not being overly used by the majority or something?

He rewrites the folders so that it plays nice with his prop internally. I'd imagine it just makes it easier to handle the code if you only have to account for a single possible case.

> drag the blade to create animations, etc.
> 
> I don't really know how you'd dummify/newbie-friendly the process that wouldn't be an unreasonable ask or become convoluted to set up, but just a thought.

You never know what might the future might hold...



> I sort of get it now, I think? Correct me if I'm super dumb and getting it wrong, but are you saying that in this use case, a blade array could define a physical neopixel blade.
> 
> So, say you had a standard neopixel blade and one of those fancy shmancy quad-star blades and had them set up that way with ID resisters to identify them, you could swap the blade in the hilt (or alternatively swap out the chassis with the proffieboard and put it in another hilt with the other blade) and suddenly have a whole different set of blade styles?
> 
> I'm trying to imagine a use case for that. I suppose like, you could have the same set of fonts and the same color styles, but when switching to a Kylo hilt you could have all your blade styles be unstable or something?
> 
> If I'm correct, I assume there's no real case where I could use that in the way I hypothesized?
> 
> > To avoid confusion, the second is what I was referring to above was that you can have multiple blade arrays with completely different sets of blades with its own set of presets.
> 
> Haha! Forgive me, but I'm confused!
> 
> Basically, as someone with currently one neopixel blade and one hilt, is there anything I could benefit from by having more than one blade array set up? At the moment I've been heavily editing a copy I downloaded of the default config that the saber came with, so there's just one array called "blade_in" and I've been sticking all blade styles under that one array (as far as I understand it).

Take a look at the Blade Arrays page:

![image](https://github.com/ryancog/ProffieConfig/assets/170381220/a244436b-a67e-4454-89a0-05c9ec9c6aa9)

Blade Awareness and Blade Arrays are two fundamentally interconnected concepts.
There's two parts to Blade Awareness. Blade ID and Blade Detect. Blade Detect uses a latching switch type mechanism with a separate pin, whereas Blade ID measures resistance between (typically) your data pin and GND.

You can also use just Blade ID with an "infinite" resistance to emulate Blade Detect, but that's besides the point.

For example if you wanted to detect if a blade that's in at all w/ Blade Detect, and then also have an ID measuring for a neopixel (blade_in at 0) and tri-cree (tricree at 40000) to differentiate between the two, you could do it like this:

![image](https://github.com/ryancog/ProffieConfig/assets/170381220/3d73076f-64fe-439a-b667-b988a33b5e8b)

Now, you'll have 3 Blade Arrays, each with their own preset arrays. But how is this useful?

Well, first and foremost in the case of Tri-Cree vs NeoPixel, they either need to be controlled differently and/or should have different setups for length. In this case having a separate preset array might be a bit annoying (having them share a preset array is possible w/ ProffieOS, it's a limitation of ProffieConfig at the moment that they can't), but alas it allows you to control these two different blade types correctly.

Or what if you had a short 28" blade and a 36" blade? You could put ID resistors in them and then make sure the blades were set to the right length.

And in the case of no_blade vs having a blade, you might want only one preset in that preset array with some no blade type sounds. For example Sabertrio does something like this and when you try to ignite the saber there's a fizzle-out sound instead. You can also change bladestyles to act differently.

So there's a few different things going on here that are all kinda interleaved.

> If I'm correct, I assume there's no real case where I could use that in the way I hypothesized?

No, not for having "Folders" of presets. Blade Arrays are really more focused on switching out hardware, with the ability to, as something as a side-feature, having different preset arrays.

> Gotcha. That's what I'd seen, so I'd somewhat assumed, but wanted to be sure. So, if I wanted to group up "in1.wav", "in2.wav", etc. I'd make a folder called "in".

Exactly.

**Comment by ryancog** [comment]
> Got it. So, you could in theory do what I said about the Kylo hardware being an unstable array?

I guess so? If you had another ID setup you could have a preset array that had a preset that had an unstable bladestyle... depends on what exactly you're looking for...

> At the moment the array is called "blade_in". Does it matter what I call the arrays? As in, is that part of the detection, or is that just for my own reference?

Entirely for your own reference. There's some backend things that use it, and it'll be used for the names of the folders state files are saved in on the SD card, but it doesn't really affect anything.

To be honest `blade_in` is the default, non-renamable and non-removable because it would've been significantly more work to allow that. Perhaps it's something for me to revisit in the future.

> Thanks for humoring me by the way. I've been enjoying chatting!

Of course!

**Comment by ryancog** [comment]
> What it seems to be doing is actually saving the color to the preset instead, as it stays after switching preset (which is weird if so because I have "no edit mode" in the prop section.

This is normal. Color change works all the time. It's not a function of edit mode. (See the "Save Color" option)

> For context, I'm on a one-button setup (and have those settings all appropriately chosen in the config tool) and the shortcut for one-button is apparently "double-tap, then hold" while in the color list, to go into color zoom.

This seems correct. I double-checked to ensure that I didn't copy things in wrong when putting the button controls into ProffieConfig, and as far as I can tell, that's what the raw info in the fett263 prop specifies.

> Additionally, on some random occasions, that "double-tap-confirmation-noise" will also switch the saber color to a dim blue.

This is odd to me. Perhaps is something I'm simply unfamiliar with, but I've no clue why this would be happening.

> I'd like to know how to revert a Fett-generated style to use the default color wheel.

I remember someone else wanting to do this and I don't recall if they figured out a way.

---

Ultimately, my answer is "I don't know." All of this has to do with Fett263's prop file specifically, and while I try to keep up with things, he's always adding new things :)

I'd recommend opening a post on [The Crucible](https://crucible.hubbe.net/) which is the proffieboard forum. Fett263 is active there and if anyone would have any suggestions/insights it'd be him.

Apologies for not being able to provide more information.
